"""initial schema

Revision ID: ea57f5283cef
Revises: 
Create Date: 2025-12-18 15:07:42.075980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea57f5283cef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('diets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('instructions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nutrition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dish_type', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cook_time_minutes', sa.Integer(), nullable=True),
    sa.Column('sweetness', sa.Float(), nullable=False),
    sa.Column('saltiness', sa.Float(), nullable=False),
    sa.Column('sourness', sa.Float(), nullable=False),
    sa.Column('bitterness', sa.Float(), nullable=False),
    sa.Column('savoriness', sa.Float(), nullable=False),
    sa.Column('fattiness', sa.Float(), nullable=False),
    sa.Column('spiciness', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('swipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('liked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swipes')
    op.drop_table('users')
    op.drop_table('recipes')
    # ### end Alembic commands ###
