from pydantic import BaseModel

# creates schema for creating a swipe (user sent)
# no datetime as that is generated by backend
class SwipeCreate(BaseModel):
    device_id: str
    recipe_id: int
    liked: bool